name: Deploy to Azur App service

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'


      - name: npm install, build, and test
        run: |
          npm install --force
          npm run build --if-present
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: node-app
          path: ./dist
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'unleashified'
          slot-name: 'Staging'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7B296A7AC2F64721AA5A9C13BE7C79DC }}
